name: NASA PROJECT CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with: 
          node-version: '18'
      - name: Install dependencies
        run: yarn install-dep
      - name: Build Project
        run: yarn build

