name: NASA PROJECT CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
      TEST_MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]
        mongodb-version: [ '4.4' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install-dep
      - name: Build Project
        run: yarn build
      - name: use MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Testing Project
        run: yarn test
    

